- CONTRIBUTORS.md
- README.md
Updating the README, adding CONTRIBUTOR info
> update readme, add contributors document

- Dockerfile
- README.md
- docker-compose.yml
- entrypoint.sh
- nginx/Dockerfile
- nginx/nginx.conf
Currently works as I put it in the README.md file.
Additional things can be added like hosting a docker image somewhere so it doesn't need to be built.
> feat(docker): Initial docker design

- cardDatabase/static/css/user_decklists_mobile.css
- cardDatabase/templates/cardDatabase/html/user_decklists.html
- cardDatabase/templates/cardDatabase/html/view_decklist.html
- cardDatabase/urls.py
- cardDatabase/views.py
> Add the public decklist option

- cardDatabase/static/js/edit_decklist.js
> [BUGFIX] Janky clipboard shenanigans

- fowsim/settings.py
If the heroku db environment variable is present use that instead so it doesn't break, fixes #122
> Adding a check to the settings.py to check heroku db environment variable

- cardDatabase/templates/cardDatabase/html/view_decklist.html
Note: I have not been able to run this locally.
> Add tooltips to card images in deck list page

- cardDatabase/static/css/base.css
- cardDatabase/static/css/bootstrap/bootstrap_dark.css
- cardDatabase/static/css/darkmode/dark_mode_overrides.css
- cardDatabase/static/css/darkmode/dark_mode_toggle.css
- cardDatabase/static/css/database_base_mobile.css
- cardDatabase/static/js/darkmode/dark_mode_toggle.js
- cardDatabase/templates/cardDatabase/html/base.html
This implements a dark theme + toggle for ForceOfWind
Base Dark theme is achieved by loading bootstrap darkmode and adjusting certain styles via a override css.
Toggle sets a cookie and cookie will be read on site load via request cookies.
Can be hot toggles since dark and light mode are loaded on load but disabled in dom.
> Add dark mode theme #62

- cardDatabase/static/js/darkmode/dark_mode_toggle.js
- cardDatabase/templates/cardDatabase/html/base.html
Functionally identical to the dark mode toggle code with a minor bugfix on preferred theme.
Just a bit of a rewrite to reorganise things and use jQuery where possible. Also added a cookie jQuery plugin to make it look a bit nicer.
> Tidy darkmode js

- cardDatabase/static/js/view_decklist_statistics.js
Hotfix for X cost cards for #140
> Fixed X cost cards in statistics

- cardDatabase/static/js/view_decklist_statistics.js
Fixed Bug with Moon will cost cards and stats.
Now counting Moon towards void since new column is unnecessaryfor 99% of decks.
> Fixed Moon will stats bug

- cardDatabase/static/js/edit_decklist.js
> fix to html character entities when saving decklist

- requirements.txt
As the title says. Updated the version to 6.0.1 for `docker-compose up -d --build` to work.
> Update PyYAML version to 6.0.1

- cardDatabase/static/js/view_decklist_statistics.js
> Fixed time will being an issue in stats

- fowsim/constants.py
Card was played at the last US GP and is not in the DB
> Added FOWMOVIE to sets

- cardDatabase/urls.py
- cardDatabase/views.py
Endpoint is public and only works on public decks
> Table Top Sim Api endpoint to get decks from

- cardDatabase/static/css/add_card.css
- cardDatabase/static/js/add_card.js
- cardDatabase/templates/cardDatabase/html/add_card.html
Added a importer for the Json files provided by @Mattaiyah 
Reads the json and shows a select to choose from to autofill fields
Does not work with images since they are not provided in the json
> Added Json importer that prefills the selected value of an uploaded file

- cardDatabase/templates/cardDatabase/html/edit_decklist_mobile.html
- cardDatabase/views.py
Fixed "bug" that lead to users not being able to save decklists on mobile
> Fixed mobile view to work with new deck type

- cardDatabase/static/css/add_card.css
- cardDatabase/static/js/add_card.js
- cardDatabase/templates/cardDatabase/html/add_card.html
Added QOL features for site admins that add cards
> Added cards upload cache and toggle to only show newest cards.

- fowsim/constants.py
Masterpiece has its own cluster and does not belong to any others
> Added Setcode for MP02 and moved masterpiece to own cluster

- cardDatabase/management/commands/incrementalCardImport.py
- cardDatabase/management/commands/incrementalCardImportLocal.py
Created command to batch import cards with without affecting old cards.
Create cardDatabase/static/cardBatchImport.json in schema of cardDatabase/static/cards.json
Upload images to folder or S3 bucket
Execute 
python manage.py incrementalCardImport
This command only works if the PR #175 has been completed since card.card_image was changed to card._card_image
> Created batch import command

- cardDatabase/static/css/darkmode/dark_mode_overrides.css
- cardDatabase/static/css/view_card.css
- cardDatabase/templates/cardDatabase/html/card_details.html
small changes to make the solo mode box things look nicer
> initial commit

- cardDatabase/static/js/tournament/admin/base.js
- cardDatabase/static/js/tournament/admin/players.js
- cardDatabase/templates/tournament/tournament_admin.html
- cardDatabase/templates/tournament/tournament_create.html
- cardDatabase/templates/tournament/tournament_detail.html
- cardDatabase/urls.py
- cardDatabase/views/tournament/admin/tournament_admin.py
- cardDatabase/views/tournament/copy_tournament.py
- Added back buttons on tournament pages
- Admin : Added detail link copy and tournament copy and fixed players js bug that showed boxes not in row
> Added new QoL features for Tournament Manager

- cardDatabase/templates/tournament/tournament_detail.html
- cardDatabase/views/tournament/admin/get_tournament_players.py
Writing now 'Unknown' in their ruler combo name
> Fixed skipping players that dont have rulers in their lists. 
